apiVersion: v1
kind: ServiceAccount
metadata:
  name: locko-operator
  namespace: locko-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: locko-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: locko-operator-role
subjects:
  - kind: ServiceAccount
    name: locko-operator
    namespace: locko-system
